# Generated by Django 3.1.7 on 2021-03-04 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sometable',
            name='author',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sometable',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
