# Generated by Django 3.1.7 on 2021-03-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicies', '0003_auto_20210309_1552'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeTable',
        ),
    ]
